version: '3'

services:
  chat.2024.dataweek.de:
    build:
      context: .
      dockerfile: Containerfile
    env_file:
      - chat.dist.env
      - chat.custom.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.dw-chat.loadbalancer.server.port=3000"
      - "traefik.http.routers.dw-chat.rule=Host(`chat.2024.dataweek.de`) || Host(`chat.2023.dataweek.de`)"
    networks:
      - web

networks:
  web:
    external: true
